# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addition.proto',
  package='helloworld',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x61\x64\x64ition.proto\x12\nhelloworld\"(\n\nAddRequest\x12\x0c\n\x04num1\x18\x01 \x01(\t\x12\x0c\n\x04num2\x18\x02 \x01(\t\"\x17\n\x08\x41\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\t2E\n\x05\x41\x64\x64\x65r\x12<\n\nAddNumbers\x12\x16.helloworld.AddRequest\x1a\x14.helloworld.AddReply\"\x00\x42\x32\n\x19io.grpc.examples.additionB\rAdditionProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='helloworld.AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='helloworld.AddRequest.num1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num2', full_name='helloworld.AddRequest.num2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=70,
)


_ADDREPLY = _descriptor.Descriptor(
  name='AddReply',
  full_name='helloworld.AddReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='helloworld.AddReply.sum', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['AddReply'] = _ADDREPLY

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDREQUEST,
  __module__ = 'addition_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.AddRequest)
  ))
_sym_db.RegisterMessage(AddRequest)

AddReply = _reflection.GeneratedProtocolMessageType('AddReply', (_message.Message,), dict(
  DESCRIPTOR = _ADDREPLY,
  __module__ = 'addition_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.AddReply)
  ))
_sym_db.RegisterMessage(AddReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031io.grpc.examples.additionB\rAdditionProtoP\001\242\002\003HLW'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class AdderStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.AddNumbers = channel.unary_unary(
          '/helloworld.Adder/AddNumbers',
          request_serializer=AddRequest.SerializeToString,
          response_deserializer=AddReply.FromString,
          )


  class AdderServicer(object):
    """The greeting service definition.
    """

    def AddNumbers(self, request, context):
      """Adds numbers
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_AdderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'AddNumbers': grpc.unary_unary_rpc_method_handler(
            servicer.AddNumbers,
            request_deserializer=AddRequest.FromString,
            response_serializer=AddReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'helloworld.Adder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaAdderServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def AddNumbers(self, request, context):
      """Adds numbers
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaAdderStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def AddNumbers(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Adds numbers
      """
      raise NotImplementedError()
    AddNumbers.future = None


  def beta_create_Adder_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('helloworld.Adder', 'AddNumbers'): AddRequest.FromString,
    }
    response_serializers = {
      ('helloworld.Adder', 'AddNumbers'): AddReply.SerializeToString,
    }
    method_implementations = {
      ('helloworld.Adder', 'AddNumbers'): face_utilities.unary_unary_inline(servicer.AddNumbers),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Adder_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('helloworld.Adder', 'AddNumbers'): AddRequest.SerializeToString,
    }
    response_deserializers = {
      ('helloworld.Adder', 'AddNumbers'): AddReply.FromString,
    }
    cardinalities = {
      'AddNumbers': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'helloworld.Adder', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
